### PR TITLE
Remove database.php from the git repo

### PR DESCRIPTION
**Pull request by icyflame**
@punit121 and @uagarwal744 Check if the version deployed on the server is working, if yes, then merge this PR.

### CODE REVIEW

**Comment by uagarwal744** [comment]
@icyflame On server, there's an error message - The configuration file database.php does not exist.

**Comment by icyflame** [comment]
@uagarwal744 Sorry! The file got deleted while changing branches.

I have created a backup now, try again.

**Comment by icyflame** [comment]
@students-alumni-cell-iitkgp/mentorship-php-team Have you tested this? Is it working?

**Comment by icyflame** [comment]
@students-alumni-cell-iitkgp/mentorship-php-team I have added the config/database.php file now. No error shown on the server now.

**Pull request merged**
