### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by punit121**

### CODE REVIEW

**Comment by icyflame** [comment]
@punit121 You and @uagarwal744 have push access to this repository. You can push directly, no need to open PR.

**Comment by icyflame** [comment]
@punit121 and @uagarwal744 
- Force pushing to master is disabled.
- Be sure to remove private credentials before pushing. (Localhost PHPMyAdmin password, username, et al)

cc @light94 @aniarya82

**Comment by mrahul17** [comment]
@icyflame @aniarya82 Are we rebuilding the portal from scratch?

**Comment by icyflame** [comment]
@light94 As it happens, they felt it would be better to move the whole portal to PHP, for better maintenance.

**Pull request closed without merging**
